#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMerced.Common.Entities
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="clinica")]
	public partial class ClinicaDataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ClinicaDataModelDataContext() : 
				base(global::ClinicaMerced.Backend.Properties.Settings.Default.clinicaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<rpt_consulta> rpt_consultas
		{
			get
			{
				return this.GetTable<rpt_consulta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rpt_consultas")]
	public partial class rpt_consulta
	{
		
		private System.DateTime _Fecha;
		
		private System.Nullable<decimal> _ArancelMutual;
		
		private System.Nullable<decimal> _Coseguro;
		
		private string _NombreProfecional;
		
		private string _NombreMutual;
		
		private string _NombreTipoConsulta;
		
		public rpt_consulta()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArancelMutual", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> ArancelMutual
		{
			get
			{
				return this._ArancelMutual;
			}
			set
			{
				if ((this._ArancelMutual != value))
				{
					this._ArancelMutual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Coseguro", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Coseguro
		{
			get
			{
				return this._Coseguro;
			}
			set
			{
				if ((this._Coseguro != value))
				{
					this._Coseguro = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProfecional", DbType="VarChar(50)")]
		public string NombreProfecional
		{
			get
			{
				return this._NombreProfecional;
			}
			set
			{
				if ((this._NombreProfecional != value))
				{
					this._NombreProfecional = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreMutual", DbType="VarChar(50)")]
		public string NombreMutual
		{
			get
			{
				return this._NombreMutual;
			}
			set
			{
				if ((this._NombreMutual != value))
				{
					this._NombreMutual = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreTipoConsulta", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string NombreTipoConsulta
		{
			get
			{
				return this._NombreTipoConsulta;
			}
			set
			{
				if ((this._NombreTipoConsulta != value))
				{
					this._NombreTipoConsulta = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
