

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk 10.0 Code Generator.
//     Runtime Version: 1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// Author: marcelo 
// Date:   Wednesday, September 21, 2011
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using ClinicaMerced.Backend.Entities;
using System.Collections.Generic;
///use TextTemplatingFileGenerator
namespace ClinicaMerced.Common.Entities
{
    #region Entities





    [XmlRoot("aspnet_MembershipList"), SerializableAttribute]
    public class aspnet_MembershipList : Fwk.Bases.Entities<aspnet_MembershipBE> { }

    [XmlInclude(typeof(aspnet_Membership)), Serializable]
    public partial class aspnet_MembershipBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                _ApplicationId = value;
            }
        }

        private global::System.Guid _ApplicationId;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                _UserId = value;
            }
        }

        private global::System.Guid _UserId;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                _Password = value;
            }
        }

        private global::System.String _Password;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 PasswordFormat
        {
            get
            {
                return _PasswordFormat;
            }
            set
            {
                _PasswordFormat = value;
            }
        }

        private global::System.Int32 _PasswordFormat;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String PasswordSalt
        {
            get
            {
                return _PasswordSalt;
            }
            set
            {
                _PasswordSalt = value;
            }
        }

        private global::System.String _PasswordSalt;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String MobilePIN
        {
            get
            {
                return _MobilePIN;
            }
            set
            {
                _MobilePIN = value;
            }
        }

        private global::System.String _MobilePIN;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                _Email = value;
            }
        }

        private global::System.String _Email;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String LoweredEmail
        {
            get
            {
                return _LoweredEmail;
            }
            set
            {
                _LoweredEmail = value;
            }
        }

        private global::System.String _LoweredEmail;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String PasswordQuestion
        {
            get
            {
                return _PasswordQuestion;
            }
            set
            {
                _PasswordQuestion = value;
            }
        }

        private global::System.String _PasswordQuestion;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String PasswordAnswer
        {
            get
            {
                return _PasswordAnswer;
            }
            set
            {
                _PasswordAnswer = value;
            }
        }

        private global::System.String _PasswordAnswer;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Boolean IsApproved
        {
            get
            {
                return _IsApproved;
            }
            set
            {
                _IsApproved = value;
            }
        }

        private global::System.Boolean _IsApproved;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Boolean IsLockedOut
        {
            get
            {
                return _IsLockedOut;
            }
            set
            {
                _IsLockedOut = value;
            }
        }

        private global::System.Boolean _IsLockedOut;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime CreateDate
        {
            get
            {
                return _CreateDate;
            }
            set
            {
                _CreateDate = value;
            }
        }

        private global::System.DateTime _CreateDate;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                _LastLoginDate = value;
            }
        }

        private global::System.DateTime _LastLoginDate;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime LastPasswordChangedDate
        {
            get
            {
                return _LastPasswordChangedDate;
            }
            set
            {
                _LastPasswordChangedDate = value;
            }
        }

        private global::System.DateTime _LastPasswordChangedDate;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime LastLockoutDate
        {
            get
            {
                return _LastLockoutDate;
            }
            set
            {
                _LastLockoutDate = value;
            }
        }

        private global::System.DateTime _LastLockoutDate;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 FailedPasswordAttemptCount
        {
            get
            {
                return _FailedPasswordAttemptCount;
            }
            set
            {
                _FailedPasswordAttemptCount = value;
            }
        }

        private global::System.Int32 _FailedPasswordAttemptCount;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime FailedPasswordAttemptWindowStart
        {
            get
            {
                return _FailedPasswordAttemptWindowStart;
            }
            set
            {
                _FailedPasswordAttemptWindowStart = value;
            }
        }

        private global::System.DateTime _FailedPasswordAttemptWindowStart;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 FailedPasswordAnswerAttemptCount
        {
            get
            {
                return _FailedPasswordAnswerAttemptCount;
            }
            set
            {
                _FailedPasswordAnswerAttemptCount = value;
            }
        }

        private global::System.Int32 _FailedPasswordAnswerAttemptCount;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime FailedPasswordAnswerAttemptWindowStart
        {
            get
            {
                return _FailedPasswordAnswerAttemptWindowStart;
            }
            set
            {
                _FailedPasswordAnswerAttemptWindowStart = value;
            }
        }

        private global::System.DateTime _FailedPasswordAnswerAttemptWindowStart;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                _Comment = value;
            }
        }

        private global::System.String _Comment;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public aspnet_MembershipBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="paspnet_Membership">Edm Model BE</param>
        public aspnet_MembershipBE(aspnet_Membership paspnet_Membership)
        {
            _ApplicationId = paspnet_Membership.ApplicationId;
            _UserId = paspnet_Membership.UserId;
            _Password = paspnet_Membership.Password;
            _PasswordFormat = paspnet_Membership.PasswordFormat;
            _PasswordSalt = paspnet_Membership.PasswordSalt;
            _MobilePIN = paspnet_Membership.MobilePIN;
            _Email = paspnet_Membership.Email;
            _LoweredEmail = paspnet_Membership.LoweredEmail;
            _PasswordQuestion = paspnet_Membership.PasswordQuestion;
            _PasswordAnswer = paspnet_Membership.PasswordAnswer;
            _IsApproved = paspnet_Membership.IsApproved;
            _IsLockedOut = paspnet_Membership.IsLockedOut;
            _CreateDate = paspnet_Membership.CreateDate;
            _LastLoginDate = paspnet_Membership.LastLoginDate;
            _LastPasswordChangedDate = paspnet_Membership.LastPasswordChangedDate;
            _LastLockoutDate = paspnet_Membership.LastLockoutDate;
            _FailedPasswordAttemptCount = paspnet_Membership.FailedPasswordAttemptCount;
            _FailedPasswordAttemptWindowStart = paspnet_Membership.FailedPasswordAttemptWindowStart;
            _FailedPasswordAnswerAttemptCount = paspnet_Membership.FailedPasswordAnswerAttemptCount;
            _FailedPasswordAnswerAttemptWindowStart = paspnet_Membership.FailedPasswordAnswerAttemptWindowStart;
            _Comment = paspnet_Membership.Comment;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="paspnet_Membership">Edm Model BE</param>
        public static explicit operator aspnet_MembershipBE(aspnet_Membership paspnet_Membership)
        {
            return new aspnet_MembershipBE(paspnet_Membership);
        }
    }





    [XmlRoot("aspnet_UsersList"), SerializableAttribute]
    public class aspnet_UsersList : Fwk.Bases.Entities<aspnet_UsersBE> { }

    [XmlInclude(typeof(aspnet_Users)), Serializable]
    public partial class aspnet_UsersBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Guid ApplicationId
        {
            get
            {
                return _ApplicationId;
            }
            set
            {
                _ApplicationId = value;
            }
        }

        private global::System.Guid _ApplicationId;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Guid UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                _UserId = value;
            }
        }

        private global::System.Guid _UserId;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                _UserName = value;
            }
        }

        private global::System.String _UserName;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String LoweredUserName
        {
            get
            {
                return _LoweredUserName;
            }
            set
            {
                _LoweredUserName = value;
            }
        }

        private global::System.String _LoweredUserName;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String MobileAlias
        {
            get
            {
                return _MobileAlias;
            }
            set
            {
                _MobileAlias = value;
            }
        }

        private global::System.String _MobileAlias;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Boolean IsAnonymous
        {
            get
            {
                return _IsAnonymous;
            }
            set
            {
                _IsAnonymous = value;
            }
        }

        private global::System.Boolean _IsAnonymous;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                _LastActivityDate = value;
            }
        }

        private global::System.DateTime _LastActivityDate;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public aspnet_UsersBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="paspnet_Users">Edm Model BE</param>
        public aspnet_UsersBE(aspnet_Users paspnet_Users)
        {
            _ApplicationId = paspnet_Users.ApplicationId;
            _UserId = paspnet_Users.UserId;
            _UserName = paspnet_Users.UserName;
            _LoweredUserName = paspnet_Users.LoweredUserName;
            _MobileAlias = paspnet_Users.MobileAlias;
            _IsAnonymous = paspnet_Users.IsAnonymous;
            _LastActivityDate = paspnet_Users.LastActivityDate;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="paspnet_Users">Edm Model BE</param>
        public static explicit operator aspnet_UsersBE(aspnet_Users paspnet_Users)
        {
            return new aspnet_UsersBE(paspnet_Users);
        }
    }





    [XmlRoot("ConsultaList"), SerializableAttribute]
    public class ConsultaList : Fwk.Bases.Entities<ConsultaBE> { }

    [XmlInclude(typeof(Consulta)), Serializable]
    public partial class ConsultaBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdConsulta
        {
            get
            {
                return _IdConsulta;
            }
            set
            {
                _IdConsulta = value;
            }
        }

        private global::System.Int32 _IdConsulta;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdTipoConsulta
        {
            get
            {
                return _IdTipoConsulta;
            }
            set
            {
                _IdTipoConsulta = value;
            }
        }

        private Nullable<global::System.Int32> _IdTipoConsulta;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdProfecional
        {
            get
            {
                return _IdProfecional;
            }
            set
            {
                _IdProfecional = value;
            }
        }

        private Nullable<global::System.Int32> _IdProfecional;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdMutual
        {
            get
            {
                return _IdMutual;
            }
            set
            {
                _IdMutual = value;
            }
        }

        private Nullable<global::System.Int32> _IdMutual;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String NroAfiliadoMutual
        {
            get
            {
                return _NroAfiliadoMutual;
            }
            set
            {
                _NroAfiliadoMutual = value;
            }
        }

        private global::System.String _NroAfiliadoMutual;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                _Fecha = value;
            }
        }

        private global::System.DateTime _Fecha;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                _Descripcion = value;
            }
        }

        private global::System.String _Descripcion;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String NombreCliente
        {
            get
            {
                return _NombreCliente;
            }
            set
            {
                _NombreCliente = value;
            }
        }

        private global::System.String _NombreCliente;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Boolean> PresentaOrden
        {
            get
            {
                return _PresentaOrden;
            }
            set
            {
                _PresentaOrden = value;
            }
        }

        private Nullable<global::System.Boolean> _PresentaOrden;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String TelefonoCliente
        {
            get
            {
                return _TelefonoCliente;
            }
            set
            {
                _TelefonoCliente = value;
            }
        }

        private global::System.String _TelefonoCliente;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Decimal> Coseguro
        {
            get
            {
                return _Coseguro;
            }
            set
            {
                _Coseguro = value;
            }
        }

        private Nullable<global::System.Decimal> _Coseguro;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Boolean> ExigeCoseguro
        {
            get
            {
                return _ExigeCoseguro;
            }
            set
            {
                _ExigeCoseguro = value;
            }
        }

        private Nullable<global::System.Boolean> _ExigeCoseguro;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Decimal> ArancelMutual
        {
            get
            {
                return _ArancelMutual;
            }
            set
            {
                _ArancelMutual = value;
            }
        }

        private Nullable<global::System.Decimal> _ArancelMutual;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                _UserName = value;
            }
        }

        private global::System.String _UserName;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public ConsultaBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="pConsulta">Edm Model BE</param>
        public ConsultaBE(Consulta pConsulta)
        {
            _IdConsulta = pConsulta.IdConsulta;
            _IdTipoConsulta = pConsulta.IdTipoConsulta;
            _IdProfecional = pConsulta.IdProfecional;
            _IdMutual = pConsulta.IdMutual;
            _NroAfiliadoMutual = pConsulta.NroAfiliadoMutual;
            _Fecha = pConsulta.Fecha;
            _Descripcion = pConsulta.Descripcion;
            _NombreCliente = pConsulta.NombreCliente;
            _PresentaOrden = pConsulta.PresentaOrden;
            _TelefonoCliente = pConsulta.TelefonoCliente;
            _Coseguro = pConsulta.Coseguro;
            _ExigeCoseguro = pConsulta.ExigeCoseguro;
            _ArancelMutual = pConsulta.ArancelMutual;
            _UserName = pConsulta.UserName;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="pConsulta">Edm Model BE</param>
        public static explicit operator ConsultaBE(Consulta pConsulta)
        {
            return new ConsultaBE(pConsulta);
        }
    }





    [XmlRoot("MutualList"), SerializableAttribute]
    public class MutualList : Fwk.Bases.Entities<MutualBE> { }

    [XmlInclude(typeof(Mutual)), Serializable]
    public partial class MutualBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdMutual
        {
            get
            {
                return _IdMutual;
            }
            set
            {
                _IdMutual = value;
            }
        }

        private global::System.Int32 _IdMutual;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                _Nombre = value;
            }
        }

        private global::System.String _Nombre;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Boolean> ExigeCoseguro
        {
            get
            {
                return _ExigeCoseguro;
            }
            set
            {
                _ExigeCoseguro = value;
            }
        }

        private Nullable<global::System.Boolean> _ExigeCoseguro;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public MutualBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="pMutual">Edm Model BE</param>
        public MutualBE(Mutual pMutual)
        {
            _IdMutual = pMutual.IdMutual;
            _Nombre = pMutual.Nombre;
            _ExigeCoseguro = pMutual.ExigeCoseguro;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="pMutual">Edm Model BE</param>
        public static explicit operator MutualBE(Mutual pMutual)
        {
            return new MutualBE(pMutual);
        }
    }





    [XmlRoot("ParamComercialList"), SerializableAttribute]
    public partial class ParamComercialList : Fwk.Bases.Entities<ParamComercialBE> { }

    [XmlInclude(typeof(ParamComercial)), Serializable]
    public partial class ParamComercialBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdParamComercial
        {
            get
            {
                return _IdParamComercial;
            }
            set
            {
                _IdParamComercial = value;
            }
        }

        private global::System.Int32 _IdParamComercial;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                _Nombre = value;
            }
        }

        private global::System.String _Nombre;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdTipoParametro
        {
            get
            {
                return _IdTipoParametro;
            }
            set
            {
                _IdTipoParametro = value;
            }
        }

        private Nullable<global::System.Int32> _IdTipoParametro;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdParamComercialRef
        {
            get
            {
                return _IdParamComercialRef;
            }
            set
            {
                _IdParamComercialRef = value;
            }
        }

        private Nullable<global::System.Int32> _IdParamComercialRef;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                _Descripcion = value;
            }
        }

        private global::System.String _Descripcion;



        /// <summary>
        /// 
        /// </summary>
        public global::System.Boolean Vigente
        {
            get
            {
                return _Vigente;
            }
            set
            {
                _Vigente = value;
            }
        }

        private global::System.Boolean _Vigente;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Guid> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                _UserId = value;
            }
        }

        private Nullable<global::System.Guid> _UserId;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String CompanyId
        {
            get
            {
                return _CompanyId;
            }
            set
            {
                _CompanyId = value;
            }
        }

        private global::System.String _CompanyId;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public ParamComercialBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="pParamComercial">Edm Model BE</param>
        public ParamComercialBE(ParamComercial pParamComercial)
        {
            _IdParamComercial = pParamComercial.IdParamComercial;
            _Nombre = pParamComercial.Nombre;
            _IdTipoParametro = pParamComercial.IdTipoParametro;
            _IdParamComercialRef = pParamComercial.IdParamComercialRef;
            _Descripcion = pParamComercial.Descripcion;
            _Vigente = pParamComercial.Vigente;
            _UserId = pParamComercial.UserId;
            _CompanyId = pParamComercial.CompanyId;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="pParamComercial">Edm Model BE</param>
        public static explicit operator ParamComercialBE(ParamComercial pParamComercial)
        {
            return new ParamComercialBE(pParamComercial);
        }
    }





    [XmlRoot("ProfecionalList"), SerializableAttribute]
    public class ProfecionalList : Fwk.Bases.Entities<ProfecionalBE> { }

    [XmlInclude(typeof(Profecional)), Serializable]
    public partial class ProfecionalBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdProfecional
        {
            get
            {
                return _IdProfecional;
            }
            set
            {
                _IdProfecional = value;
            }
        }

        private global::System.Int32 _IdProfecional;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                _Nombre = value;
            }
        }

        private global::System.String _Nombre;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdEspecialidad
        {
            get
            {
                return _IdEspecialidad;
            }
            set
            {
                _IdEspecialidad = value;
            }
        }

        private Nullable<global::System.Int32> _IdEspecialidad;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Guid> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                _UserId = value;
            }
        }

        private Nullable<global::System.Guid> _UserId;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                _Apellido = value;
            }
        }

        private global::System.String _Apellido;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdTipoProfecional
        {
            get
            {
                return _IdTipoProfecional;
            }
            set
            {
                _IdTipoProfecional = value;
            }
        }

        private Nullable<global::System.Int32> _IdTipoProfecional;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public ProfecionalBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="pProfecional">Edm Model BE</param>
        public ProfecionalBE(Profecional pProfecional)
        {
            _IdProfecional = pProfecional.IdProfecional;
            _Nombre = pProfecional.Nombre;
            _IdEspecialidad = pProfecional.IdEspecialidad;
            _UserId = pProfecional.UserId;
            _Apellido = pProfecional.Apellido;
            _IdTipoProfecional = pProfecional.IdTipoProfecional;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="pProfecional">Edm Model BE</param>
        public static explicit operator ProfecionalBE(Profecional pProfecional)
        {
            return new ProfecionalBE(pProfecional);
        }
    }





    [XmlRoot("Rpt_Consulta_FullList"), SerializableAttribute]
    public class Rpt_Consulta_FullList : Fwk.Bases.Entities<Rpt_Consulta_FullBE> { }

    [XmlInclude(typeof(Rpt_Consulta_Full)), Serializable]
    public partial class Rpt_Consulta_FullBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdProfecional
        {
            get
            {
                return _IdProfecional;
            }
            set
            {
                _IdProfecional = value;
            }
        }

        private Nullable<global::System.Int32> _IdProfecional;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdMutual
        {
            get
            {
                return _IdMutual;
            }
            set
            {
                _IdMutual = value;
            }
        }

        private Nullable<global::System.Int32> _IdMutual;



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                _Fecha = value;
            }
        }

        private global::System.DateTime _Fecha;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Boolean> PresentaOrden
        {
            get
            {
                return _PresentaOrden;
            }
            set
            {
                _PresentaOrden = value;
            }
        }

        private Nullable<global::System.Boolean> _PresentaOrden;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Decimal> Coseguro
        {
            get
            {
                return _Coseguro;
            }
            set
            {
                _Coseguro = value;
            }
        }

        private Nullable<global::System.Decimal> _Coseguro;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Boolean> ExigeCoseguro
        {
            get
            {
                return _ExigeCoseguro;
            }
            set
            {
                _ExigeCoseguro = value;
            }
        }

        private Nullable<global::System.Boolean> _ExigeCoseguro;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Decimal> ArancelMutual
        {
            get
            {
                return _ArancelMutual;
            }
            set
            {
                _ArancelMutual = value;
            }
        }

        private Nullable<global::System.Decimal> _ArancelMutual;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdTipoConsulta
        {
            get
            {
                return _IdTipoConsulta;
            }
            set
            {
                _IdTipoConsulta = value;
            }
        }

        private Nullable<global::System.Int32> _IdTipoConsulta;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String TipoConsulta
        {
            get
            {
                return _TipoConsulta;
            }
            set
            {
                _TipoConsulta = value;
            }
        }

        private global::System.String _TipoConsulta;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Profecional
        {
            get
            {
                return _Profecional;
            }
            set
            {
                _Profecional = value;
            }
        }

        private global::System.String _Profecional;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Mutual
        {
            get
            {
                return _Mutual;
            }
            set
            {
                _Mutual = value;
            }
        }

        private global::System.String _Mutual;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public Rpt_Consulta_FullBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="pRpt_Consulta_Full">Edm Model BE</param>
        public Rpt_Consulta_FullBE(Rpt_Consulta_Full pRpt_Consulta_Full)
        {
            _IdProfecional = pRpt_Consulta_Full.IdProfecional;
            _IdMutual = pRpt_Consulta_Full.IdMutual;
            _Fecha = pRpt_Consulta_Full.Fecha;
            _PresentaOrden = pRpt_Consulta_Full.PresentaOrden;
            _Coseguro = pRpt_Consulta_Full.Coseguro;
            _ExigeCoseguro = pRpt_Consulta_Full.ExigeCoseguro;
            _ArancelMutual = pRpt_Consulta_Full.ArancelMutual;
            _IdTipoConsulta = pRpt_Consulta_Full.IdTipoConsulta;
            _TipoConsulta = pRpt_Consulta_Full.TipoConsulta;
            _Profecional = pRpt_Consulta_Full.Profecional;
            _Mutual = pRpt_Consulta_Full.Mutual;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="pRpt_Consulta_Full">Edm Model BE</param>
        public static explicit operator Rpt_Consulta_FullBE(Rpt_Consulta_Full pRpt_Consulta_Full)
        {
            return new Rpt_Consulta_FullBE(pRpt_Consulta_Full);
        }
    }





    [XmlRoot("TipoParametroList"), SerializableAttribute]
    public class TipoParametroList : Fwk.Bases.Entities<TipoParametroBE> { }

    [XmlInclude(typeof(TipoParametro)), Serializable]
    public partial class TipoParametroBE : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdTipoParametro
        {
            get
            {
                return _IdTipoParametro;
            }
            set
            {
                _IdTipoParametro = value;
            }
        }

        private global::System.Int32 _IdTipoParametro;



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                _Nombre = value;
            }
        }

        private global::System.String _Nombre;



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdTipoParametroRelacion
        {
            get
            {
                return _IdTipoParametroRelacion;
            }
            set
            {
                _IdTipoParametroRelacion = value;
            }
        }

        private Nullable<global::System.Int32> _IdTipoParametroRelacion;



        #endregion


        /// <summary>
        /// Empty Constructor
        /// </summary>
        public TipoParametroBE() { }

        /// <summary>
        /// Constructor from Model Entity
        /// Framework BE --> Edm Entity Model 
        /// </summary>
        /// <param name="pTipoParametro">Edm Model BE</param>
        public TipoParametroBE(TipoParametro pTipoParametro)
        {
            _IdTipoParametro = pTipoParametro.IdTipoParametro;
            _Nombre = pTipoParametro.Nombre;
            _IdTipoParametroRelacion = pTipoParametro.IdTipoParametroRelacion;
        }


        /// <summary>
        /// Overload equal operator
        /// Framework BE = Edm Entity Model 
        /// </summary>
        /// <param name="pTipoParametro">Edm Model BE</param>
        public static explicit operator TipoParametroBE(TipoParametro pTipoParametro)
        {
            return new TipoParametroBE(pTipoParametro);
        }
    }

    #endregion

}
//namespace ClinicaMerced.Common.Entities
//{






//    [XmlRoot("aspnet_MembershipList"), SerializableAttribute]
//    public class aspnet_MembershipList : Fwk.Bases.Entities<aspnet_MembershipBE> { }

//    [XmlInclude(typeof(aspnet_Membership)), Serializable]
//    public partial class aspnet_MembershipBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Guid ApplicationId
//        {
//            get
//            {
//                return _ApplicationId;
//            }
//            set
//            {
//                _ApplicationId = value;
//            }
//        }

//        private global::System.Guid _ApplicationId;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Guid UserId
//        {
//            get
//            {
//                return _UserId;
//            }
//            set
//            {
//                _UserId = value;
//            }
//        }

//        private global::System.Guid _UserId;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Password
//        {
//            get
//            {
//                return _Password;
//            }
//            set
//            {
//                _Password = value;
//            }
//        }

//        private global::System.String _Password;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 PasswordFormat
//        {
//            get
//            {
//                return _PasswordFormat;
//            }
//            set
//            {
//                _PasswordFormat = value;
//            }
//        }

//        private global::System.Int32 _PasswordFormat;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String PasswordSalt
//        {
//            get
//            {
//                return _PasswordSalt;
//            }
//            set
//            {
//                _PasswordSalt = value;
//            }
//        }

//        private global::System.String _PasswordSalt;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String MobilePIN
//        {
//            get
//            {
//                return _MobilePIN;
//            }
//            set
//            {
//                _MobilePIN = value;
//            }
//        }

//        private global::System.String _MobilePIN;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Email
//        {
//            get
//            {
//                return _Email;
//            }
//            set
//            {
//                _Email = value;
//            }
//        }

//        private global::System.String _Email;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String LoweredEmail
//        {
//            get
//            {
//                return _LoweredEmail;
//            }
//            set
//            {
//                _LoweredEmail = value;
//            }
//        }

//        private global::System.String _LoweredEmail;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String PasswordQuestion
//        {
//            get
//            {
//                return _PasswordQuestion;
//            }
//            set
//            {
//                _PasswordQuestion = value;
//            }
//        }

//        private global::System.String _PasswordQuestion;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String PasswordAnswer
//        {
//            get
//            {
//                return _PasswordAnswer;
//            }
//            set
//            {
//                _PasswordAnswer = value;
//            }
//        }

//        private global::System.String _PasswordAnswer;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Boolean IsApproved
//        {
//            get
//            {
//                return _IsApproved;
//            }
//            set
//            {
//                _IsApproved = value;
//            }
//        }

//        private global::System.Boolean _IsApproved;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Boolean IsLockedOut
//        {
//            get
//            {
//                return _IsLockedOut;
//            }
//            set
//            {
//                _IsLockedOut = value;
//            }
//        }

//        private global::System.Boolean _IsLockedOut;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime CreateDate
//        {
//            get
//            {
//                return _CreateDate;
//            }
//            set
//            {
//                _CreateDate = value;
//            }
//        }

//        private global::System.DateTime _CreateDate;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime LastLoginDate
//        {
//            get
//            {
//                return _LastLoginDate;
//            }
//            set
//            {
//                _LastLoginDate = value;
//            }
//        }

//        private global::System.DateTime _LastLoginDate;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime LastPasswordChangedDate
//        {
//            get
//            {
//                return _LastPasswordChangedDate;
//            }
//            set
//            {
//                _LastPasswordChangedDate = value;
//            }
//        }

//        private global::System.DateTime _LastPasswordChangedDate;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime LastLockoutDate
//        {
//            get
//            {
//                return _LastLockoutDate;
//            }
//            set
//            {
//                _LastLockoutDate = value;
//            }
//        }

//        private global::System.DateTime _LastLockoutDate;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 FailedPasswordAttemptCount
//        {
//            get
//            {
//                return _FailedPasswordAttemptCount;
//            }
//            set
//            {
//                _FailedPasswordAttemptCount = value;
//            }
//        }

//        private global::System.Int32 _FailedPasswordAttemptCount;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime FailedPasswordAttemptWindowStart
//        {
//            get
//            {
//                return _FailedPasswordAttemptWindowStart;
//            }
//            set
//            {
//                _FailedPasswordAttemptWindowStart = value;
//            }
//        }

//        private global::System.DateTime _FailedPasswordAttemptWindowStart;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 FailedPasswordAnswerAttemptCount
//        {
//            get
//            {
//                return _FailedPasswordAnswerAttemptCount;
//            }
//            set
//            {
//                _FailedPasswordAnswerAttemptCount = value;
//            }
//        }

//        private global::System.Int32 _FailedPasswordAnswerAttemptCount;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime FailedPasswordAnswerAttemptWindowStart
//        {
//            get
//            {
//                return _FailedPasswordAnswerAttemptWindowStart;
//            }
//            set
//            {
//                _FailedPasswordAnswerAttemptWindowStart = value;
//            }
//        }

//        private global::System.DateTime _FailedPasswordAnswerAttemptWindowStart;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Comment
//        {
//            get
//            {
//                return _Comment;
//            }
//            set
//            {
//                _Comment = value;
//            }
//        }

//        private global::System.String _Comment;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public aspnet_MembershipBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="paspnet_Membership">Edm Model BE</param>
//        public aspnet_MembershipBE(aspnet_Membership paspnet_Membership)
//        {
//            _ApplicationId = paspnet_Membership.ApplicationId;
//            _UserId = paspnet_Membership.UserId;
//            _Password = paspnet_Membership.Password;
//            _PasswordFormat = paspnet_Membership.PasswordFormat;
//            _PasswordSalt = paspnet_Membership.PasswordSalt;
//            _MobilePIN = paspnet_Membership.MobilePIN;
//            _Email = paspnet_Membership.Email;
//            _LoweredEmail = paspnet_Membership.LoweredEmail;
//            _PasswordQuestion = paspnet_Membership.PasswordQuestion;
//            _PasswordAnswer = paspnet_Membership.PasswordAnswer;
//            _IsApproved = paspnet_Membership.IsApproved;
//            _IsLockedOut = paspnet_Membership.IsLockedOut;
//            _CreateDate = paspnet_Membership.CreateDate;
//            _LastLoginDate = paspnet_Membership.LastLoginDate;
//            _LastPasswordChangedDate = paspnet_Membership.LastPasswordChangedDate;
//            _LastLockoutDate = paspnet_Membership.LastLockoutDate;
//            _FailedPasswordAttemptCount = paspnet_Membership.FailedPasswordAttemptCount;
//            _FailedPasswordAttemptWindowStart = paspnet_Membership.FailedPasswordAttemptWindowStart;
//            _FailedPasswordAnswerAttemptCount = paspnet_Membership.FailedPasswordAnswerAttemptCount;
//            _FailedPasswordAnswerAttemptWindowStart = paspnet_Membership.FailedPasswordAnswerAttemptWindowStart;
//            _Comment = paspnet_Membership.Comment;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="paspnet_Membership">Edm Model BE</param>
//        public static explicit operator aspnet_MembershipBE(aspnet_Membership paspnet_Membership)
//        {
//            return new aspnet_MembershipBE(paspnet_Membership);
//        }
//    }





//    [XmlRoot("aspnet_UsersList"), SerializableAttribute]
//    public class aspnet_UsersList : Fwk.Bases.Entities<aspnet_UsersBE> { }

//    [XmlInclude(typeof(aspnet_Users)), Serializable]
//    public partial class aspnet_UsersBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Guid ApplicationId
//        {
//            get
//            {
//                return _ApplicationId;
//            }
//            set
//            {
//                _ApplicationId = value;
//            }
//        }

//        private global::System.Guid _ApplicationId;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Guid UserId
//        {
//            get
//            {
//                return _UserId;
//            }
//            set
//            {
//                _UserId = value;
//            }
//        }

//        private global::System.Guid _UserId;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String UserName
//        {
//            get
//            {
//                return _UserName;
//            }
//            set
//            {
//                _UserName = value;
//            }
//        }

//        private global::System.String _UserName;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String LoweredUserName
//        {
//            get
//            {
//                return _LoweredUserName;
//            }
//            set
//            {
//                _LoweredUserName = value;
//            }
//        }

//        private global::System.String _LoweredUserName;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String MobileAlias
//        {
//            get
//            {
//                return _MobileAlias;
//            }
//            set
//            {
//                _MobileAlias = value;
//            }
//        }

//        private global::System.String _MobileAlias;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Boolean IsAnonymous
//        {
//            get
//            {
//                return _IsAnonymous;
//            }
//            set
//            {
//                _IsAnonymous = value;
//            }
//        }

//        private global::System.Boolean _IsAnonymous;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime LastActivityDate
//        {
//            get
//            {
//                return _LastActivityDate;
//            }
//            set
//            {
//                _LastActivityDate = value;
//            }
//        }

//        private global::System.DateTime _LastActivityDate;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public aspnet_UsersBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="paspnet_Users">Edm Model BE</param>
//        public aspnet_UsersBE(aspnet_Users paspnet_Users)
//        {
//            _ApplicationId = paspnet_Users.ApplicationId;
//            _UserId = paspnet_Users.UserId;
//            _UserName = paspnet_Users.UserName;
//            _LoweredUserName = paspnet_Users.LoweredUserName;
//            _MobileAlias = paspnet_Users.MobileAlias;
//            _IsAnonymous = paspnet_Users.IsAnonymous;
//            _LastActivityDate = paspnet_Users.LastActivityDate;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="paspnet_Users">Edm Model BE</param>
//        public static explicit operator aspnet_UsersBE(aspnet_Users paspnet_Users)
//        {
//            return new aspnet_UsersBE(paspnet_Users);
//        }
//    }





//    [XmlRoot("ConsultaList"), SerializableAttribute]
//    public class ConsultaList : Fwk.Bases.Entities<ConsultaBE> { }

//    [XmlInclude(typeof(Consulta)), Serializable]
//    public partial class ConsultaBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 IdConsulta
//        {
//            get
//            {
//                return _IdConsulta;
//            }
//            set
//            {
//                _IdConsulta = value;
//            }
//        }

//        private global::System.Int32 _IdConsulta;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdTipoConsulta
//        {
//            get
//            {
//                return _IdTipoConsulta;
//            }
//            set
//            {
//                _IdTipoConsulta = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdTipoConsulta;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdProfecional
//        {
//            get
//            {
//                return _IdProfecional;
//            }
//            set
//            {
//                _IdProfecional = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdProfecional;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdMutual
//        {
//            get
//            {
//                return _IdMutual;
//            }
//            set
//            {
//                _IdMutual = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdMutual;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String NroAfiliadoMutual
//        {
//            get
//            {
//                return _NroAfiliadoMutual;
//            }
//            set
//            {
//                _NroAfiliadoMutual = value;
//            }
//        }

//        private global::System.String _NroAfiliadoMutual;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime? Fecha
//        {
//            get
//            {
//                return _Fecha;
//            }
//            set
//            {
//                _Fecha = value;
//            }
//        }

//        private global::System.DateTime? _Fecha;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Descripcion
//        {
//            get
//            {
//                return _Descripcion;
//            }
//            set
//            {
//                _Descripcion = value;
//            }
//        }

//        private global::System.String _Descripcion;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String NombreCliente
//        {
//            get
//            {
//                return _NombreCliente;
//            }
//            set
//            {
//                _NombreCliente = value;
//            }
//        }

//        private global::System.String _NombreCliente;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Boolean> PresentaOrden
//        {
//            get
//            {
//                return _PresentaOrden;
//            }
//            set
//            {
//                _PresentaOrden = value;
//            }
//        }

//        private Nullable<global::System.Boolean> _PresentaOrden;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String TelefonoCliente
//        {
//            get
//            {
//                return _TelefonoCliente;
//            }
//            set
//            {
//                _TelefonoCliente = value;
//            }
//        }

//        private global::System.String _TelefonoCliente;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Decimal> Coseguro
//        {
//            get
//            {
//                return _Coseguro;
//            }
//            set
//            {
//                _Coseguro = value;
//            }
//        }

//        private Nullable<global::System.Decimal> _Coseguro;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Boolean> ExigeCoseguro
//        {
//            get
//            {
//                return _ExigeCoseguro;
//            }
//            set
//            {
//                _ExigeCoseguro = value;
//            }
//        }

//        private Nullable<global::System.Boolean> _ExigeCoseguro;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Decimal> ArancelMutual
//        {
//            get
//            {
//                return _ArancelMutual;
//            }
//            set
//            {
//                _ArancelMutual = value;
//            }
//        }

//        private Nullable<global::System.Decimal> _ArancelMutual;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public ConsultaBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="pConsulta">Edm Model BE</param>
//        public ConsultaBE(Consulta pConsulta)
//        {
//            _IdConsulta = pConsulta.IdConsulta;
//            _IdTipoConsulta = pConsulta.IdTipoConsulta;
//            _IdProfecional = pConsulta.IdProfecional;
//            _IdMutual = pConsulta.IdMutual;
//            _NroAfiliadoMutual = pConsulta.NroAfiliadoMutual;
//            _Fecha = pConsulta.Fecha;
//            _Descripcion = pConsulta.Descripcion;
//            _NombreCliente = pConsulta.NombreCliente;
//            _PresentaOrden = pConsulta.PresentaOrden;
//            _TelefonoCliente = pConsulta.TelefonoCliente;
//            _Coseguro = pConsulta.Coseguro;
//            _ExigeCoseguro = pConsulta.ExigeCoseguro;
//            _ArancelMutual = pConsulta.ArancelMutual;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="pConsulta">Edm Model BE</param>
//        public static explicit operator ConsultaBE(Consulta pConsulta)
//        {
//            return new ConsultaBE(pConsulta);
//        }
//    }





//    [XmlRoot("MutualList"), SerializableAttribute]
//    public class MutualList : Fwk.Bases.Entities<MutualBE> { }

//    [XmlInclude(typeof(Mutual)), Serializable]
//    public partial class MutualBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 IdMutual
//        {
//            get
//            {
//                return _IdMutual;
//            }
//            set
//            {
//                _IdMutual = value;
//            }
//        }

//        private global::System.Int32 _IdMutual;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Nombre
//        {
//            get
//            {
//                return _Nombre;
//            }
//            set
//            {
//                _Nombre = value;
//            }
//        }

//        private global::System.String _Nombre;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Boolean> ExigeCoseguro
//        {
//            get
//            {
//                return _ExigeCoseguro;
//            }
//            set
//            {
//                _ExigeCoseguro = value;
//            }
//        }

//        private Nullable<global::System.Boolean> _ExigeCoseguro;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public MutualBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="pMutual">Edm Model BE</param>
//        public MutualBE(Mutual pMutual)
//        {
//            _IdMutual = pMutual.IdMutual;
//            _Nombre = pMutual.Nombre;
//            _ExigeCoseguro = pMutual.ExigeCoseguro;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="pMutual">Edm Model BE</param>
//        public static explicit operator MutualBE(Mutual pMutual)
//        {
//            return new MutualBE(pMutual);
//        }
//    }





//    [XmlRoot("ParamComercialList"), SerializableAttribute]
//    public partial class ParamComercialList : Fwk.Bases.Entities<ParamComercialBE> 
//    {
       

//    }

//    [XmlInclude(typeof(ParamComercial)), Serializable]
//    public partial class ParamComercialBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 IdParamComercial
//        {
//            get
//            {
//                return _IdParamComercial;
//            }
//            set
//            {
//                _IdParamComercial = value;
//            }
//        }

//        private global::System.Int32 _IdParamComercial;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Nombre
//        {
//            get
//            {
//                return _Nombre;
//            }
//            set
//            {
//                _Nombre = value;
//            }
//        }

//        private global::System.String _Nombre;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdTipoParametro
//        {
//            get
//            {
//                return _IdTipoParametro;
//            }
//            set
//            {
//                _IdTipoParametro = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdTipoParametro;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdParamComercialRef
//        {
//            get
//            {
//                return _IdParamComercialRef;
//            }
//            set
//            {
//                _IdParamComercialRef = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdParamComercialRef;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Descripcion
//        {
//            get
//            {
//                return _Descripcion;
//            }
//            set
//            {
//                _Descripcion = value;
//            }
//        }

//        private global::System.String _Descripcion;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Boolean Vigente
//        {
//            get
//            {
//                return _Vigente;
//            }
//            set
//            {
//                _Vigente = value;
//            }
//        }

//        private global::System.Boolean _Vigente;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Guid> UserId
//        {
//            get
//            {
//                return _UserId;
//            }
//            set
//            {
//                _UserId = value;
//            }
//        }

//        private Nullable<global::System.Guid> _UserId;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String CompanyId
//        {
//            get
//            {
//                return _CompanyId;
//            }
//            set
//            {
//                _CompanyId = value;
//            }
//        }

//        private global::System.String _CompanyId;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public ParamComercialBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="pParamComercial">Edm Model BE</param>
//        public ParamComercialBE(ParamComercial pParamComercial)
//        {
//            _IdParamComercial = pParamComercial.IdParamComercial;
//            _Nombre = pParamComercial.Nombre;
//            _IdTipoParametro = pParamComercial.IdTipoParametro;
//            _IdParamComercialRef = pParamComercial.IdParamComercialRef;
//            _Descripcion = pParamComercial.Descripcion;
//            _Vigente = pParamComercial.Vigente;
//            _UserId = pParamComercial.UserId;
//            _CompanyId = pParamComercial.CompanyId;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="pParamComercial">Edm Model BE</param>
//        public static explicit operator ParamComercialBE(ParamComercial pParamComercial)
//        {
//            return new ParamComercialBE(pParamComercial);
//        }
//    }





//    [XmlRoot("ProfecionalList"), SerializableAttribute]
//    public class ProfecionalList : Fwk.Bases.Entities<ProfecionalBE> 
//    {
       
//    }

//    [XmlInclude(typeof(Profecional)), Serializable]
//    public partial class ProfecionalBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 IdProfecional
//        {
//            get
//            {
//                return _IdProfecional;
//            }
//            set
//            {
//                _IdProfecional = value;
//            }
//        }

//        private global::System.Int32 _IdProfecional;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Nombre
//        {
//            get
//            {
//                return _Nombre;
//            }
//            set
//            {
//                _Nombre = value;
//            }
//        }

//        private global::System.String _Nombre;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdEspecialidad
//        {
//            get
//            {
//                return _IdEspecialidad;
//            }
//            set
//            {
//                _IdEspecialidad = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdEspecialidad;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Guid> UserId
//        {
//            get
//            {
//                return _UserId;
//            }
//            set
//            {
//                _UserId = value;
//            }
//        }

//        private Nullable<global::System.Guid> _UserId;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Apellido
//        {
//            get
//            {
//                return _Apellido;
//            }
//            set
//            {
//                _Apellido = value;
//            }
//        }

//        private global::System.String _Apellido;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public ProfecionalBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="pProfecional">Edm Model BE</param>
//        public ProfecionalBE(Profecional pProfecional)
//        {
//            _IdProfecional = pProfecional.IdProfecional;
//            _Nombre = pProfecional.Nombre;
//            _IdEspecialidad = pProfecional.IdEspecialidad;
//            _UserId = pProfecional.UserId;
//            _Apellido = pProfecional.Apellido;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="pProfecional">Edm Model BE</param>
//        public static explicit operator ProfecionalBE(Profecional pProfecional)
//        {
//            return new ProfecionalBE(pProfecional);
//        }
//    }





//    [XmlRoot("Rpt_Consulta_FullList"), SerializableAttribute]
//    public class Rpt_Consulta_FullList : Fwk.Bases.Entities<Rpt_Consulta_FullBE> { }

//    [XmlInclude(typeof(Rpt_Consulta_Full)), Serializable]
//    public partial class Rpt_Consulta_FullBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdProfecional
//        {
//            get
//            {
//                return _IdProfecional;
//            }
//            set
//            {
//                _IdProfecional = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdProfecional;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdMutual
//        {
//            get
//            {
//                return _IdMutual;
//            }
//            set
//            {
//                _IdMutual = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdMutual;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.DateTime Fecha
//        {
//            get
//            {
//                return _Fecha;
//            }
//            set
//            {
//                _Fecha = value;
//            }
//        }

//        private global::System.DateTime _Fecha;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Boolean> PresentaOrden
//        {
//            get
//            {
//                return _PresentaOrden;
//            }
//            set
//            {
//                _PresentaOrden = value;
//            }
//        }

//        private Nullable<global::System.Boolean> _PresentaOrden;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Decimal> Coseguro
//        {
//            get
//            {
//                return _Coseguro;
//            }
//            set
//            {
//                _Coseguro = value;
//            }
//        }

//        private Nullable<global::System.Decimal> _Coseguro;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Boolean> ExigeCoseguro
//        {
//            get
//            {
//                return _ExigeCoseguro;
//            }
//            set
//            {
//                _ExigeCoseguro = value;
//            }
//        }

//        private Nullable<global::System.Boolean> _ExigeCoseguro;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Decimal> ArancelMutual
//        {
//            get
//            {
//                return _ArancelMutual;
//            }
//            set
//            {
//                _ArancelMutual = value;
//            }
//        }

//        private Nullable<global::System.Decimal> _ArancelMutual;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdTipoConsulta
//        {
//            get
//            {
//                return _IdTipoConsulta;
//            }
//            set
//            {
//                _IdTipoConsulta = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdTipoConsulta;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String TipoConsulta
//        {
//            get
//            {
//                return _TipoConsulta;
//            }
//            set
//            {
//                _TipoConsulta = value;
//            }
//        }

//        private global::System.String _TipoConsulta;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Profecional
//        {
//            get
//            {
//                return _Profecional;
//            }
//            set
//            {
//                _Profecional = value;
//            }
//        }

//        private global::System.String _Profecional;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Mutual
//        {
//            get
//            {
//                return _Mutual;
//            }
//            set
//            {
//                _Mutual = value;
//            }
//        }

//        private global::System.String _Mutual;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public Rpt_Consulta_FullBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="pRpt_Consulta_Full">Edm Model BE</param>
//        public Rpt_Consulta_FullBE(Rpt_Consulta_Full pRpt_Consulta_Full)
//        {
//            _IdProfecional = pRpt_Consulta_Full.IdProfecional;
//            _IdMutual = pRpt_Consulta_Full.IdMutual;
//            _Fecha = pRpt_Consulta_Full.Fecha;
//            _PresentaOrden = pRpt_Consulta_Full.PresentaOrden;
//            _Coseguro = pRpt_Consulta_Full.Coseguro;
//            _ExigeCoseguro = pRpt_Consulta_Full.ExigeCoseguro;
//            _ArancelMutual = pRpt_Consulta_Full.ArancelMutual;
//            _IdTipoConsulta = pRpt_Consulta_Full.IdTipoConsulta;
//            _TipoConsulta = pRpt_Consulta_Full.TipoConsulta;
//            _Profecional = pRpt_Consulta_Full.Profecional;
//            _Mutual = pRpt_Consulta_Full.Mutual;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="pRpt_Consulta_Full">Edm Model BE</param>
//        public static explicit operator Rpt_Consulta_FullBE(Rpt_Consulta_Full pRpt_Consulta_Full)
//        {
//            return new Rpt_Consulta_FullBE(pRpt_Consulta_Full);
//        }
//    }





//    [XmlRoot("TipoParametroList"), SerializableAttribute]
//    public class TipoParametroList : Fwk.Bases.Entities<TipoParametroBE> { }

//    [XmlInclude(typeof(TipoParametro)), Serializable]
//    public partial class TipoParametroBE : Fwk.Bases.Entity
//    {
//        #region Primitive Properties

//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.Int32 IdTipoParametro
//        {
//            get
//            {
//                return _IdTipoParametro;
//            }
//            set
//            {
//                _IdTipoParametro = value;
//            }
//        }

//        private global::System.Int32 _IdTipoParametro;



//        /// <summary>
//        /// 
//        /// </summary>
//        public global::System.String Nombre
//        {
//            get
//            {
//                return _Nombre;
//            }
//            set
//            {
//                _Nombre = value;
//            }
//        }

//        private global::System.String _Nombre;



//        /// <summary>
//        /// 
//        /// </summary>
//        public Nullable<global::System.Int32> IdTipoParametroRelacion
//        {
//            get
//            {
//                return _IdTipoParametroRelacion;
//            }
//            set
//            {
//                _IdTipoParametroRelacion = value;
//            }
//        }

//        private Nullable<global::System.Int32> _IdTipoParametroRelacion;



//        #endregion


//        /// <summary>
//        /// Empty Constructor
//        /// </summary>
//        public TipoParametroBE() { }

//        /// <summary>
//        /// Constructor from Model Entity
//        /// Framework BE --> Edm Entity Model 
//        /// </summary>
//        /// <param name="pTipoParametro">Edm Model BE</param>
//        public TipoParametroBE(TipoParametro pTipoParametro)
//        {
//            _IdTipoParametro = pTipoParametro.IdTipoParametro;
//            _Nombre = pTipoParametro.Nombre;
//            _IdTipoParametroRelacion = pTipoParametro.IdTipoParametroRelacion;
//        }


//        /// <summary>
//        /// Overload equal operator
//        /// Framework BE = Edm Entity Model 
//        /// </summary>
//        /// <param name="pTipoParametro">Edm Model BE</param>
//        public static explicit operator TipoParametroBE(TipoParametro pTipoParametro)
//        {
//            return new TipoParametroBE(pTipoParametro);
//        }
//    }


//}



