#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaMerced.Common.Entities.Angel
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="clinica")]
	public partial class AngelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertnomenclator_practice_group(nomenclator_practice_group instance);
    partial void Updatenomenclator_practice_group(nomenclator_practice_group instance);
    partial void Deletenomenclator_practice_group(nomenclator_practice_group instance);
    partial void Insertnomenclator(nomenclator instance);
    partial void Updatenomenclator(nomenclator instance);
    partial void Deletenomenclator(nomenclator instance);
    partial void Insertnomenclator_expenses_value(nomenclator_expenses_value instance);
    partial void Updatenomenclator_expenses_value(nomenclator_expenses_value instance);
    partial void Deletenomenclator_expenses_value(nomenclator_expenses_value instance);
    partial void Insertnomenclator_practice(nomenclator_practice instance);
    partial void Updatenomenclator_practice(nomenclator_practice instance);
    partial void Deletenomenclator_practice(nomenclator_practice instance);
    partial void Insertmedical_insurance_company(medical_insurance_company instance);
    partial void Updatemedical_insurance_company(medical_insurance_company instance);
    partial void Deletemedical_insurance_company(medical_insurance_company instance);
    partial void Insertmedicine_covered_plan(medicine_covered_plan instance);
    partial void Updatemedicine_covered_plan(medicine_covered_plan instance);
    partial void Deletemedicine_covered_plan(medicine_covered_plan instance);
    partial void Insertmedical_insurance_plan(medical_insurance_plan instance);
    partial void Updatemedical_insurance_plan(medical_insurance_plan instance);
    partial void Deletemedical_insurance_plan(medical_insurance_plan instance);
    #endregion
		
		public AngelDataContext() : 
				base(global::ClinicaMerced.Backend.Properties.Settings.Default.clinicaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AngelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AngelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AngelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AngelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<nomenclator_practice_group> nomenclator_practice_groups
		{
			get
			{
				return this.GetTable<nomenclator_practice_group>();
			}
		}
		
		public System.Data.Linq.Table<nomenclator> nomenclators
		{
			get
			{
				return this.GetTable<nomenclator>();
			}
		}
		
		public System.Data.Linq.Table<nomenclator_expenses_value> nomenclator_expenses_values
		{
			get
			{
				return this.GetTable<nomenclator_expenses_value>();
			}
		}
		
		public System.Data.Linq.Table<nomenclator_practice> nomenclator_practices
		{
			get
			{
				return this.GetTable<nomenclator_practice>();
			}
		}
		
		public System.Data.Linq.Table<medical_insurance_company> medical_insurance_companies
		{
			get
			{
				return this.GetTable<medical_insurance_company>();
			}
		}
		
		public System.Data.Linq.Table<medicine_covered_plan> medicine_covered_plans
		{
			get
			{
				return this.GetTable<medicine_covered_plan>();
			}
		}
		
		public System.Data.Linq.Table<medical_insurance_plan> medical_insurance_plans
		{
			get
			{
				return this.GetTable<medical_insurance_plan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nomenclator_practice_group")]
	public partial class nomenclator_practice_group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _code;
		
		private string _description;
		
		private System.Nullable<int> _nomenclator_id;
		
		private System.Nullable<int> _trigger_practice_id;
		
		private System.Nullable<decimal> _payment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onnomenclator_idChanging(System.Nullable<int> value);
    partial void Onnomenclator_idChanged();
    partial void Ontrigger_practice_idChanging(System.Nullable<int> value);
    partial void Ontrigger_practice_idChanged();
    partial void OnpaymentChanging(System.Nullable<decimal> value);
    partial void OnpaymentChanged();
    #endregion
		
		public nomenclator_practice_group()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(16)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomenclator_id", DbType="Int")]
		public System.Nullable<int> nomenclator_id
		{
			get
			{
				return this._nomenclator_id;
			}
			set
			{
				if ((this._nomenclator_id != value))
				{
					this.Onnomenclator_idChanging(value);
					this.SendPropertyChanging();
					this._nomenclator_id = value;
					this.SendPropertyChanged("nomenclator_id");
					this.Onnomenclator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trigger_practice_id", DbType="Int")]
		public System.Nullable<int> trigger_practice_id
		{
			get
			{
				return this._trigger_practice_id;
			}
			set
			{
				if ((this._trigger_practice_id != value))
				{
					this.Ontrigger_practice_idChanging(value);
					this.SendPropertyChanging();
					this._trigger_practice_id = value;
					this.SendPropertyChanged("trigger_practice_id");
					this.Ontrigger_practice_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_payment", DbType="Decimal(11,2)")]
		public System.Nullable<decimal> payment
		{
			get
			{
				return this._payment;
			}
			set
			{
				if ((this._payment != value))
				{
					this.OnpaymentChanging(value);
					this.SendPropertyChanging();
					this._payment = value;
					this.SendPropertyChanged("payment");
					this.OnpaymentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nomenclator")]
	public partial class nomenclator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _code;
		
		private string _description;
		
		private System.Nullable<int> _owner_id1;
		
		private System.Nullable<int> _owner_id2;
		
		private string _owner_kind;
		
		private string _owner_description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onowner_id1Changing(System.Nullable<int> value);
    partial void Onowner_id1Changed();
    partial void Onowner_id2Changing(System.Nullable<int> value);
    partial void Onowner_id2Changed();
    partial void Onowner_kindChanging(string value);
    partial void Onowner_kindChanged();
    partial void Onowner_descriptionChanging(string value);
    partial void Onowner_descriptionChanged();
    #endregion
		
		public nomenclator()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(16)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(200)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_id1", DbType="Int")]
		public System.Nullable<int> owner_id1
		{
			get
			{
				return this._owner_id1;
			}
			set
			{
				if ((this._owner_id1 != value))
				{
					this.Onowner_id1Changing(value);
					this.SendPropertyChanging();
					this._owner_id1 = value;
					this.SendPropertyChanged("owner_id1");
					this.Onowner_id1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_id2", DbType="Int")]
		public System.Nullable<int> owner_id2
		{
			get
			{
				return this._owner_id2;
			}
			set
			{
				if ((this._owner_id2 != value))
				{
					this.Onowner_id2Changing(value);
					this.SendPropertyChanging();
					this._owner_id2 = value;
					this.SendPropertyChanged("owner_id2");
					this.Onowner_id2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_kind", DbType="NChar(10)")]
		public string owner_kind
		{
			get
			{
				return this._owner_kind;
			}
			set
			{
				if ((this._owner_kind != value))
				{
					this.Onowner_kindChanging(value);
					this.SendPropertyChanging();
					this._owner_kind = value;
					this.SendPropertyChanged("owner_kind");
					this.Onowner_kindChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_description", DbType="VarChar(200)")]
		public string owner_description
		{
			get
			{
				return this._owner_description;
			}
			set
			{
				if ((this._owner_description != value))
				{
					this.Onowner_descriptionChanging(value);
					this.SendPropertyChanging();
					this._owner_description = value;
					this.SendPropertyChanged("owner_description");
					this.Onowner_descriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nomenclator_expenses_values")]
	public partial class nomenclator_expenses_value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _code;
		
		private string _description;
		
		private System.Nullable<decimal> _expense_value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onexpense_valueChanging(System.Nullable<decimal> value);
    partial void Onexpense_valueChanged();
    #endregion
		
		public nomenclator_expenses_value()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expense_value", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> expense_value
		{
			get
			{
				return this._expense_value;
			}
			set
			{
				if ((this._expense_value != value))
				{
					this.Onexpense_valueChanging(value);
					this.SendPropertyChanging();
					this._expense_value = value;
					this.SendPropertyChanged("expense_value");
					this.Onexpense_valueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nomenclator_practice")]
	public partial class nomenclator_practice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nomenclator_id;
		
		private int _practice_id;
		
		private string _especialist_expense_code;
		
		private string _ayudant_expense_code;
		
		private string _anestesist_expense_code;
		
		private string _adhoc_expense_code;
		
		private System.Nullable<int> _lack;
		
		private System.Nullable<decimal> _copayment;
		
		private System.Nullable<char> _authorization;
		
		private System.Nullable<int> _top_for_period;
		
		private System.Nullable<int> _period;
		
		private System.Nullable<System.DateTime> _time_begin;
		
		private System.Nullable<decimal> _especialist_subtotal;
		
		private System.Nullable<decimal> _ayudant_subtotal;
		
		private System.Nullable<decimal> _anestesist_subtotal;
		
		private System.Nullable<decimal> _adhoc_subtotal;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<decimal> _totalpayment;
		
		private string _blame;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnomenclator_idChanging(int value);
    partial void Onnomenclator_idChanged();
    partial void Onpractice_idChanging(int value);
    partial void Onpractice_idChanged();
    partial void Onespecialist_expense_codeChanging(string value);
    partial void Onespecialist_expense_codeChanged();
    partial void Onayudant_expense_codeChanging(string value);
    partial void Onayudant_expense_codeChanged();
    partial void Onanestesist_expense_codeChanging(string value);
    partial void Onanestesist_expense_codeChanged();
    partial void Onadhoc_expense_codeChanging(string value);
    partial void Onadhoc_expense_codeChanged();
    partial void OnlackChanging(System.Nullable<int> value);
    partial void OnlackChanged();
    partial void OncopaymentChanging(System.Nullable<decimal> value);
    partial void OncopaymentChanged();
    partial void OnauthorizationChanging(System.Nullable<char> value);
    partial void OnauthorizationChanged();
    partial void Ontop_for_periodChanging(System.Nullable<int> value);
    partial void Ontop_for_periodChanged();
    partial void OnperiodChanging(System.Nullable<int> value);
    partial void OnperiodChanged();
    partial void Ontime_beginChanging(System.Nullable<System.DateTime> value);
    partial void Ontime_beginChanged();
    partial void Onespecialist_subtotalChanging(System.Nullable<decimal> value);
    partial void Onespecialist_subtotalChanged();
    partial void Onayudant_subtotalChanging(System.Nullable<decimal> value);
    partial void Onayudant_subtotalChanged();
    partial void Onanestesist_subtotalChanging(System.Nullable<decimal> value);
    partial void Onanestesist_subtotalChanged();
    partial void Onadhoc_subtotalChanging(System.Nullable<decimal> value);
    partial void Onadhoc_subtotalChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void OntotalpaymentChanging(System.Nullable<decimal> value);
    partial void OntotalpaymentChanged();
    partial void OnblameChanging(string value);
    partial void OnblameChanged();
    #endregion
		
		public nomenclator_practice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomenclator_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nomenclator_id
		{
			get
			{
				return this._nomenclator_id;
			}
			set
			{
				if ((this._nomenclator_id != value))
				{
					this.Onnomenclator_idChanging(value);
					this.SendPropertyChanging();
					this._nomenclator_id = value;
					this.SendPropertyChanged("nomenclator_id");
					this.Onnomenclator_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_practice_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int practice_id
		{
			get
			{
				return this._practice_id;
			}
			set
			{
				if ((this._practice_id != value))
				{
					this.Onpractice_idChanging(value);
					this.SendPropertyChanging();
					this._practice_id = value;
					this.SendPropertyChanged("practice_id");
					this.Onpractice_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especialist_expense_code", DbType="VarChar(5)")]
		public string especialist_expense_code
		{
			get
			{
				return this._especialist_expense_code;
			}
			set
			{
				if ((this._especialist_expense_code != value))
				{
					this.Onespecialist_expense_codeChanging(value);
					this.SendPropertyChanging();
					this._especialist_expense_code = value;
					this.SendPropertyChanged("especialist_expense_code");
					this.Onespecialist_expense_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ayudant_expense_code", DbType="VarChar(5)")]
		public string ayudant_expense_code
		{
			get
			{
				return this._ayudant_expense_code;
			}
			set
			{
				if ((this._ayudant_expense_code != value))
				{
					this.Onayudant_expense_codeChanging(value);
					this.SendPropertyChanging();
					this._ayudant_expense_code = value;
					this.SendPropertyChanged("ayudant_expense_code");
					this.Onayudant_expense_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anestesist_expense_code", DbType="VarChar(5)")]
		public string anestesist_expense_code
		{
			get
			{
				return this._anestesist_expense_code;
			}
			set
			{
				if ((this._anestesist_expense_code != value))
				{
					this.Onanestesist_expense_codeChanging(value);
					this.SendPropertyChanging();
					this._anestesist_expense_code = value;
					this.SendPropertyChanged("anestesist_expense_code");
					this.Onanestesist_expense_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adhoc_expense_code", DbType="VarChar(5)")]
		public string adhoc_expense_code
		{
			get
			{
				return this._adhoc_expense_code;
			}
			set
			{
				if ((this._adhoc_expense_code != value))
				{
					this.Onadhoc_expense_codeChanging(value);
					this.SendPropertyChanging();
					this._adhoc_expense_code = value;
					this.SendPropertyChanged("adhoc_expense_code");
					this.Onadhoc_expense_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lack", DbType="Int")]
		public System.Nullable<int> lack
		{
			get
			{
				return this._lack;
			}
			set
			{
				if ((this._lack != value))
				{
					this.OnlackChanging(value);
					this.SendPropertyChanging();
					this._lack = value;
					this.SendPropertyChanged("lack");
					this.OnlackChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_copayment", DbType="Decimal(11,2)")]
		public System.Nullable<decimal> copayment
		{
			get
			{
				return this._copayment;
			}
			set
			{
				if ((this._copayment != value))
				{
					this.OncopaymentChanging(value);
					this.SendPropertyChanging();
					this._copayment = value;
					this.SendPropertyChanged("copayment");
					this.OncopaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[authorization]", Storage="_authorization", DbType="Char(1)")]
		public System.Nullable<char> authorization
		{
			get
			{
				return this._authorization;
			}
			set
			{
				if ((this._authorization != value))
				{
					this.OnauthorizationChanging(value);
					this.SendPropertyChanging();
					this._authorization = value;
					this.SendPropertyChanged("authorization");
					this.OnauthorizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_top_for_period", DbType="Int")]
		public System.Nullable<int> top_for_period
		{
			get
			{
				return this._top_for_period;
			}
			set
			{
				if ((this._top_for_period != value))
				{
					this.Ontop_for_periodChanging(value);
					this.SendPropertyChanging();
					this._top_for_period = value;
					this.SendPropertyChanged("top_for_period");
					this.Ontop_for_periodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_period", DbType="Int")]
		public System.Nullable<int> period
		{
			get
			{
				return this._period;
			}
			set
			{
				if ((this._period != value))
				{
					this.OnperiodChanging(value);
					this.SendPropertyChanging();
					this._period = value;
					this.SendPropertyChanged("period");
					this.OnperiodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time_begin", DbType="DateTime")]
		public System.Nullable<System.DateTime> time_begin
		{
			get
			{
				return this._time_begin;
			}
			set
			{
				if ((this._time_begin != value))
				{
					this.Ontime_beginChanging(value);
					this.SendPropertyChanging();
					this._time_begin = value;
					this.SendPropertyChanged("time_begin");
					this.Ontime_beginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_especialist_subtotal", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> especialist_subtotal
		{
			get
			{
				return this._especialist_subtotal;
			}
			set
			{
				if ((this._especialist_subtotal != value))
				{
					this.Onespecialist_subtotalChanging(value);
					this.SendPropertyChanging();
					this._especialist_subtotal = value;
					this.SendPropertyChanged("especialist_subtotal");
					this.Onespecialist_subtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ayudant_subtotal", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> ayudant_subtotal
		{
			get
			{
				return this._ayudant_subtotal;
			}
			set
			{
				if ((this._ayudant_subtotal != value))
				{
					this.Onayudant_subtotalChanging(value);
					this.SendPropertyChanging();
					this._ayudant_subtotal = value;
					this.SendPropertyChanged("ayudant_subtotal");
					this.Onayudant_subtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anestesist_subtotal", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> anestesist_subtotal
		{
			get
			{
				return this._anestesist_subtotal;
			}
			set
			{
				if ((this._anestesist_subtotal != value))
				{
					this.Onanestesist_subtotalChanging(value);
					this.SendPropertyChanging();
					this._anestesist_subtotal = value;
					this.SendPropertyChanged("anestesist_subtotal");
					this.Onanestesist_subtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adhoc_subtotal", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> adhoc_subtotal
		{
			get
			{
				return this._adhoc_subtotal;
			}
			set
			{
				if ((this._adhoc_subtotal != value))
				{
					this.Onadhoc_subtotalChanging(value);
					this.SendPropertyChanging();
					this._adhoc_subtotal = value;
					this.SendPropertyChanged("adhoc_subtotal");
					this.Onadhoc_subtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_totalpayment", DbType="Decimal(11,4)")]
		public System.Nullable<decimal> totalpayment
		{
			get
			{
				return this._totalpayment;
			}
			set
			{
				if ((this._totalpayment != value))
				{
					this.OntotalpaymentChanging(value);
					this.SendPropertyChanging();
					this._totalpayment = value;
					this.SendPropertyChanged("totalpayment");
					this.OntotalpaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_blame", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string blame
		{
			get
			{
				return this._blame;
			}
			set
			{
				if ((this._blame != value))
				{
					this.OnblameChanging(value);
					this.SendPropertyChanging();
					this._blame = value;
					this.SendPropertyChanged("blame");
					this.OnblameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.medical_insurance_company")]
	public partial class medical_insurance_company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _entity_id1;
		
		private System.Nullable<short> _country_id;
		
		private string _name;
		
		private System.Nullable<int> _rnos;
		
		private string _etc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onentity_id1Changing(string value);
    partial void Onentity_id1Changed();
    partial void Oncountry_idChanging(System.Nullable<short> value);
    partial void Oncountry_idChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnrnosChanging(System.Nullable<int> value);
    partial void OnrnosChanged();
    partial void OnetcChanging(string value);
    partial void OnetcChanged();
    #endregion
		
		public medical_insurance_company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entity_id1", DbType="VarChar(16)")]
		public string entity_id1
		{
			get
			{
				return this._entity_id1;
			}
			set
			{
				if ((this._entity_id1 != value))
				{
					this.Onentity_id1Changing(value);
					this.SendPropertyChanging();
					this._entity_id1 = value;
					this.SendPropertyChanged("entity_id1");
					this.Onentity_id1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country_id", DbType="SmallInt")]
		public System.Nullable<short> country_id
		{
			get
			{
				return this._country_id;
			}
			set
			{
				if ((this._country_id != value))
				{
					this.Oncountry_idChanging(value);
					this.SendPropertyChanging();
					this._country_id = value;
					this.SendPropertyChanged("country_id");
					this.Oncountry_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(255)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rnos", DbType="Int")]
		public System.Nullable<int> rnos
		{
			get
			{
				return this._rnos;
			}
			set
			{
				if ((this._rnos != value))
				{
					this.OnrnosChanging(value);
					this.SendPropertyChanging();
					this._rnos = value;
					this.SendPropertyChanged("rnos");
					this.OnrnosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etc", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string etc
		{
			get
			{
				return this._etc;
			}
			set
			{
				if ((this._etc != value))
				{
					this.OnetcChanging(value);
					this.SendPropertyChanging();
					this._etc = value;
					this.SendPropertyChanged("etc");
					this.OnetcChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.medicine_covered_plan")]
	public partial class medicine_covered_plan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mic_plan_id;
		
		private string _comercial_code;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmic_plan_idChanging(int value);
    partial void Onmic_plan_idChanged();
    partial void Oncomercial_codeChanging(string value);
    partial void Oncomercial_codeChanged();
    #endregion
		
		public medicine_covered_plan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mic_plan_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int mic_plan_id
		{
			get
			{
				return this._mic_plan_id;
			}
			set
			{
				if ((this._mic_plan_id != value))
				{
					this.Onmic_plan_idChanging(value);
					this.SendPropertyChanging();
					this._mic_plan_id = value;
					this.SendPropertyChanged("mic_plan_id");
					this.Onmic_plan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comercial_code", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string comercial_code
		{
			get
			{
				return this._comercial_code;
			}
			set
			{
				if ((this._comercial_code != value))
				{
					this.Oncomercial_codeChanging(value);
					this.SendPropertyChanging();
					this._comercial_code = value;
					this.SendPropertyChanged("comercial_code");
					this.Oncomercial_codeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.medical_insurance_plan")]
	public partial class medical_insurance_plan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _medical_insurance_company_id;
		
		private string _code;
		
		private string _description;
		
		private System.Nullable<int> _nomenclator_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onmedical_insurance_company_idChanging(System.Nullable<int> value);
    partial void Onmedical_insurance_company_idChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onnomenclator_idChanging(System.Nullable<int> value);
    partial void Onnomenclator_idChanged();
    #endregion
		
		public medical_insurance_plan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medical_insurance_company_id", DbType="Int")]
		public System.Nullable<int> medical_insurance_company_id
		{
			get
			{
				return this._medical_insurance_company_id;
			}
			set
			{
				if ((this._medical_insurance_company_id != value))
				{
					this.Onmedical_insurance_company_idChanging(value);
					this.SendPropertyChanging();
					this._medical_insurance_company_id = value;
					this.SendPropertyChanged("medical_insurance_company_id");
					this.Onmedical_insurance_company_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="VarChar(50)")]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomenclator_id", DbType="Int")]
		public System.Nullable<int> nomenclator_id
		{
			get
			{
				return this._nomenclator_id;
			}
			set
			{
				if ((this._nomenclator_id != value))
				{
					this.Onnomenclator_idChanging(value);
					this.SendPropertyChanging();
					this._nomenclator_id = value;
					this.SendPropertyChanged("nomenclator_id");
					this.Onnomenclator_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
