
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk 10.0 Code Generator.
//     Runtime Version: 10.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//</auto-generated>
//   Author: marcelo 
//   Date:  9/20/2011
// ==============================================================================


using System;
using System.Data;
using System.Collections.Generic;
using Fwk.Bases;

using ClinicaMerced.Common.ISVC.SearchAllProfecionales;

namespace ClinicaMercedBackEnd.SVC
{
    public class SearchAllProfecionalesService : BusinessService<SearchAllProfecionalesReq, SearchAllProfecionalesRes>
    {
        public override SearchAllProfecionalesRes Execute(SearchAllProfecionalesReq req)
        {
            SearchAllProfecionalesRes res = new SearchAllProfecionalesRes();


            //----------------------------
            // Implement your code here..
            //----------------------------

            return res;
        }
    }
}

