

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk 10.0 Code Generator.
//     Runtime Version: 10.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//</auto-generated>
//   Author: marcelo 
//   Date:  9/20/2011
// ==============================================================================


using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Fwk.Bases;
using System.Xml.Serialization;


namespace ClinicaMerced.Common.ISVC.SearchAllProfecionales
{

    #region [Request]
    [Serializable]
    public class SearchAllProfecionalesReq : Request<Params>/// If you hasn´t any returns value you can use : Request<DummyContract> and remove Params class
    {
        public SearchAllProfecionalesReq()
        {
            base.ServiceName = "SearchAllProfecionalesService";
        }
    }

    #region [BussinesData]
    [XmlInclude(typeof(Params)), Serializable]
    public class Params : Entity
    {

    }

    #endregion
    #endregion

    #region [Response]
    [Serializable]
    public class SearchAllProfecionalesRes : Response<Result> ///  If you hasn´t any returns value you can use : Request<DummyContract> and remove Params class
    {
    }

    #region [BussinesData]

    [XmlInclude(typeof(Result)), Serializable]
    public class Result : Entity
    {


    }

    #endregion
    #endregion
}

